# Generated by Django 3.0.7 on 2020-07-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('pwd', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_img')),
                ('term', models.BooleanField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=100)),
                ('date_joining', models.DateTimeField(auto_now_add=True, null=True)),
                ('subjects', models.CharField(choices=[('chem', 'Chemistry'), ('phy', 'Physics'), ('bio', 'Biology')], max_length=100)),
                ('upload_cv', models.FileField(blank=True, null=True, upload_to='doc\\')),
                ('phon', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
